version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_DB: hatchout
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
